### ISSUE TITLE
STM32F730 Memory descriptor fails

### ISSUE THREAD

**Issue by Edgs** [IntergatedCircuits/LibUsbDfu#2]
When connecting to an STM32F730, the usbDevice gives a descriptor string of:
"@Internal Flash  /0x08000000/04*016Kg,01*64Kg,03*128Kg\0"
for the Memory description.
In the STM device itself, the descriptor string includes a single trailing '\0' character within the length of the string, and this is interpreted by the usbDevice as a trailing "\0" (2 characters) on the end of the string, as seen above.
This then fails the SeMemoryLayoutRegex and aborts the process.
Editing the string to remove the "\0" in debug 'fixes' the problem.

So, this appears to be a failure to handle unexpected descriptor string contents as parsed by LibUsbDotNet.
I don't know if there are options for IUsbInterface to parse this differently (and just truncate the string at the zero) or if it could be stripped off in LibUsbDfu.
(Strictly speaking, the actual zero in the descriptor itself shouldn't really be there, but it is.)

**Comment by benedekkupper** [comment]
Well this really is a bug of the STM32 ROM bootloader implementation. That being said, it's not really possible to do anything about it where it's broken, we have to find a sensible workaround that doesn't produce other side effects. I think this fix is suitable.

**Comment by Edgs** [comment]
Thanks for looking at this, but that solution does not fix the problem.
The trailing zero chars in the descriptor are being read by UsbLibDotNet and translated into the two characters '\','0' (i.e. a string "\0") not the single character '\0'.
My solution:
**I added the characters "(?:\0)*" just before the last '$' in the regex SeMemoryLayoutRegex.**
This causes the regex to ignore any trailing "\0" at the end of the line.  Just to confuse things, that \0 in the regex should actually be \\0 and it is interpreted as such.  It required \\0 when testing externally.

It is only the SeMemoryLayoutRegex.Match(dfuSeFormat) which fails - the rest of the parsing works fine whether those trailing characters are there or not.

**Comment by benedekkupper** [comment]
Are you sure that this character translation only happens in LibUsbDotNet, i.e. not done by the OS driver for example? Could you give me a screenshot of the device in [usbview.exe](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/usbview)? And maybe also dump the ROM code with a utility? (If the ROM area isn't directly accessible by a debugger, you could copy it to RAM with a simple firmware, and then dump that RAM area.)

**Comment by Edgs** [comment]
I don't know where the character translation happens, so it could be in the driver.  The driver is an STM driver 1.1.0 07/05/2018.
USBView actually stalls on that string, and doesn't render anything after it, as seen here:
![USBView](https://user-images.githubusercontent.com/10948591/89130642-718bf200-d4fe-11ea-9e56-ec1584dffaa1.png)

Here also is the raw descriptor in the STM32 RAM as viewed while debugging (the ROM image doesn't appear to contain the raw descriptor strings):
![Firmware](https://user-images.githubusercontent.com/10948591/89130673-ad26bc00-d4fe-11ea-88d6-9bb64bb71716.png)
I also highlighted the `OTP Memory` string as it is even worse, with 10 trailing null characters, but they are definitely just null characters at this point.

Finally, here is the resulting string in DeviceProgramming, at the point where it is causing the problem:
![DeviceProgramming](https://user-images.githubusercontent.com/10948591/89130803-e90e5100-d4ff-11ea-8583-6f156e8ae2fa.png)

The strings are the same in the LibUsbDotNet object, so it is not caused by anything that happens in DeviceProgramming itself.

**Comment by benedekkupper** [comment]
I checked what LibUsbDotNet is actually doing, it's only calling `Encoding.ASCII.GetString()` on the received buffer. I've set up a simple test to replicate the events, and test the fix:

```C#
static bool TrailingTest()
{
    int trailingzeroes = 1;

    // start with valid string
    string good = "@Internal Flash /0x08000000/04*016Kg,01*64Kg,03*128Kg";

    // simulate issue: put into bytes, append zeroes
    byte[] buffer = Encoding.ASCII.GetBytes(good);
    Array.Resize<byte>(ref buffer, buffer.Length + trailingzeroes);

    // encode it back
    string bad = Encoding.ASCII.GetString(buffer, 0, buffer.Length);

    // perform countermeasure
    string fix = bad.TrimEnd(new char[] { '\0' });

    // check regex
    var result = SeMemoryLayoutRegex.Match(fix);
    Console.WriteLine(result.Success ? "Success" : "Fail");
    return result.Success;
}
```

This test passes for me, so the same should also work for you with 664e661.

What you stated above
> The trailing zero chars in the descriptor are being read by UsbLibDotNet and translated into the two characters '','0' (i.e. a string "\0") not the single character '\0'.

is not the case, it is only the Visual Studio debugger showing you that way. Also if you add "(?:\0)*" to the regex that only matches the 0x00 bytes, not the "\0" string, for that you'd need to escape the backslash character separately.
