### ISSUE TITLE
crossplatform / multitarget release

### ISSUE THREAD

**Issue by Canomation** [IntergatedCircuits/LibUsbDfu#4]
Hello, at first cool and fine work to bring dfu capability to c#. 

It works in windows with zadics winusb drivers very good. In linux with rules 
(SUBSYSTEM=="usb", ATTR{idVendor}=="0483", ATTR{idProduct}=="df11", MODE="0666") 
the libusbdotnet can't open the dfu device and device.cs throws "The device doesn't have valid DFU interface".

I used the same arguments on both platforms, other dfu-tools like dfu-util or the stm programmer works with
user rights. For me, it seems to be a problem with libusbdotnet, but maybe you can make a workaround or fix
it.
Best regard, Martin

**Comment by benedekkupper** [comment]
Hi Martin,

Thanks for bringing this issue to our attention. The exception you're getting means that LibUsbDotNet did find a device, but the IsDfuInterface check fails for some reason. Do you have a chance to debug which conditions aren't met there?

**Comment by vitalijusb85** [comment]
Hello, 
I have same issue whit STM board vendorid==0483 and ProductId == df1. 
How I managed to find out the problem is whit the Interface Custom descriptor. In the Linux system, I get 0 but in windows, I get 1.  Maybe we can avoid this in the Linux system? 

Thanks
Best regard, Vitalijus

**Comment by benedekkupper** [comment]
We cannot work around that, the custom descriptor contains vital parameters that are used by this library. We need to find how Linux/libusb exposes this descriptor from the entire configuration descriptor of the USB device. I myself don't have a Linux setup to debug this.

**Comment by vitalijusb85** [comment]
Hi,
Thanks for the fast answer.  So what I figure out, is that in Linux  LibUsbDotNet.Info can't get or recognize DFU functional descriptor. I think it is the main reason why it not working.

**Comment by benedekkupper** [comment]
Thank you for the investigation and the upstream bug report! It is indeed the problem as you describe. I was able to reproduce also on Windows, by using Zadig tool to swap out the WinUsb driver to libusb-win32 one. I have added a workaround, by refetching and reparsing the whole configuration descriptor. Let me know if the changes fix the problem for you.

**Comment by vitalijusb85** [comment]
Hi,
Thank you for the fast and good workaround. I think whit interfaces are good but I have one issue.  I think it has to do with MonoApi version.  How do I understand we missing one parameter in the method?

![image](https://user-images.githubusercontent.com/34238776/177086926-06901742-e779-4c38-8433-b135540dc70d.png)

**Comment by benedekkupper** [comment]
Now that I cannot reproduce at all on Windows. You can try with the [nonullobjects ](https://github.com/IntergatedCircuits/LibUsbDfu/tree/nonullobjects) branch and let me know of the result.

**Comment by vitalijusb85** [comment]
Hi, tested all. All works very well. So thank you a lot for your help.  If you merge those two branches, your project will work in the Linux system.

**Comment by benedekkupper** [comment]
Thanks for your support in testing and verification! I have created a new release out of this resolution, you can also include the library via Nuget if you prefer ;)
